# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

project 'Bungee.xcodeproj'

target 'Bungee' do

pod 'Batch'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

end

target 'BungeeTests' do

end

